Refactor code to modules
TahenyBELGUITH/Awesome_books_ES6 pull request #1
Opened 2022-04-25 09:49 UTC by TahenyBELGUITH

1️⃣  Created a new directory and initialized it with git.
2️⃣  Used npm init -y command to create package.json file.
3️⃣  Created the entry point for my JavaScript code called index.js
4️⃣  Created index.css file for my styles.
5️⃣  Created the main index.html file. Linked my index.js and index.css files there.
6️⃣  Created a directory called modules.
7️⃣  Re-created my Awesome books app following the rules:

> Used ES6 syntax.
> Divided my code into modules. 
> Kept all functionalities of the app without errors.
> Used let and const in a correct way.
> Displayed the current date below the navigation bar.
> For this requirement I used a library [Luxon](https://moment.github.io/luxon/#/install?id=es6)

2022-04-25 10:08 UTC, TedLivist reviewed
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @TahenyBELGUITH,

Good job so far!
✔️ Good documentation
✔️ Modularization of code
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-25 10:08 UTC, TedLivist commented on modules/DataBook.js
> +}
- [ ] In keeping with the ES6 syntax, kindly refactor your function to an arrow function.

2022-04-25 10:08 UTC, TedLivist commented on index.js
> +}
- [ ] Kindly refactor your function to an arrow function.

2022-04-25 10:08 UTC, TedLivist commented on modules/DataBook.js
> +  bookSection.innerHTML = '';
- [ ] Kindly refactor your functions to be arrow functions.

  ```
  export const clearData = () => {
    ...
  }
  ```

2022-04-26 08:25 UTC, TedLivist requested changes
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @TahenyBELGUITH,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a Pull Request with failing linters

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-04-26 08:55 UTC, mikethreels approved these changes
Hi Tahtouha, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 08:57 UTC, merged